services:
  rss-feed-service:
    build: ./news_rss
    container_name: rss_feed_container
    ports:
      - "8002:8000" # Espone la porta 8000 del container sulla 8002 locale
    volumes:
      - ./news_rss:/app # Mappa il codice sorgente in fanta-data-service folder dentro il container in /app
  aggregator-service:
    build: ./news_aggregator
    container_name: news_aggregator_container
    ports:
      - "8003:8000" # Espone la porta 8000 del container sulla 8003 locale
    volumes:
      - ./news_aggregator:/app # Mappa il codice sorgente in fanta-data-service folder dentro il container in /app
    environment:
      # L'URL usa il nome del servizio "service_b" come hostname
      - RSS_URL=http://rss-feed-service:8000
    depends_on:
      - rss-feed-service
