services: # Data Layer Service: database interface
  rss-feed-service:
    build: .
    container_name: news_aggregator
    ports:
      - "8003:8000" # Espone la porta 8000 del container sulla 8001 locale
    volumes:
      - .:/app # Mappa il codice sorgente in fanta-data-service folder dentro il container in /app
