services: # Data Layer Service: database interface
  rss-feed-service:
    build: .
    container_name: html_scraper_container
    ports:
      - "8034:8000" # Espone la porta 8000 del container sulla 8004 locale
    volumes:
      - .:/app # Mappa il codice sorgente in fanta-data-service folder dentro il container in /app
